### ISSUE TITLE
Is bidriectional "sync" supported

### ISSUE THREAD

**Issue by shawnholt** [christianwach/civicrm-wp-member-sync#12]
The readme seems to indicate that changes in civicrm are reflected in WP but not the other way around.  I'm researching ways to use woocommerce + subscriptions + memberships to sync back to civicrm.  Would this be a useful solution for that?

**Comment by christianwach** [comment]
No, it's only one way to WordPress.

**Comment by shawnholt** [comment]
Any thoughts on letting wordpress (via woocommerce) memberships create users+groups or membership levels in civicrm?  Think this code would be a good place to build-on?

**Comment by christianwach** [comment]
You are certainly welcome grab any code you think might be useful, like API calls etc. But in the end what you're after is a CiviCRM WooCommerce Sync plugin, which this one isn't. I have little experience with WooCommerce, but a brief scan of their code reveals a whole host of documented hooks that you can employ to achieve your aims.

**Comment by shawnholt** [comment]
ok, will look into it.  for those interested here ... yes we do want woocommerce but for subscriptions products, the status is like membership status and the membership module tracks that nicely.  This is data we want  for reporting and maintaining in the CRM,  (ie. send mailing to active subscribers/members, reporting, etc.)

**Comment by christianwach** [comment]
Okay, so here's what I would do to get what you want out-of-the-box (or mostly so)...

[This WooCommerce extension](https://docs.woothemes.com/document/product-support/) gives you "product groups" for BuddyPress, whereby a purchase auto-adds the purchaser to a BuddyPress group. [BP Groups CiviCRM Sync](https://wordpress.org/plugins/bp-groups-civicrm-sync/) would then sync the user to a CiviCRM "Mailing List" group.
