### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by sportman1280** [christianwach/civicrm-wp-member-sync#15]
Plugin does not seem to be PHP 7.0 compatible, as I receive errors when activating it.

Error Message: 
Fatal error: 'break' not in the 'loop' or 'switch' context in /var/www/html/wp-content/plugins/civicrm-wp-member-sync/civi-wp-ms-admin.php on line 1583

**Comment by christianwach** [comment]
@sportman1280 Thanks for the report - looks like the `break` statement was left over from a previous refactoring. You can comment that line out until I roll out a new version.

**Comment by sportman1280** [comment]
Yep, my resolution was to comment out the breaks.

**Comment by christianwach** [comment]
@sportman1280 Does this commit work for you now? I'll push to the WordPress repo if so.

**Comment by christianwach** [comment]
@sportman1280 I ask because I have heard that CiviCRM itself can be, *ahem*, fickle when running under PHP 7 - one of the reasons I do not do so as yet. I'm going to push the update to the WordPress repo anyway, in case others encounter this.

Thanks again.

**Comment by sportman1280** [comment]
@christianwach that worked!  I just upgraded to PHP 7 today, we'll see how it goes

**Comment by christianwach** [comment]
@sportman1280 Good news. Thanks again for the report.
