### ISSUE TITLE
Association Rules for method roles returns incorrect error

### ISSUE THREAD

**Issue by EventConsulting** [christianwach/civicrm-wp-member-sync#2]
Using CiviCRM 4.5.5.
Using CiviCRM Hook Tester (4.5 - version 0.2) wordpress.php - both tried as replacement or custom php directory
Using CiviCRM WordPress Member Sync (version 0.2)
Using Members (version 0.2.4

When trying to add association role for the "Roles" method for any combination of settings, including:

an existing CiviMember Membership Type, a WordPress Role created by Members, Current Status: New/Current/Grace, Expire Status: Expired/Pending/Cancelled/Deceased and Expiry Role: Subscripber

Always returns an empty "Add Assiation Rule" page (none of the settings remain) with the following error:

Please select a WordPress Role
You can not have the same Status Rule registered as both "Current" and "Expired"

Of course, I did select a WordPress Role and I didn't select a satus rule for both "Current" and "Expired".

**Comment by christianwach** [comment]
@EventConsulting Good catch. Thanks! (I almost never use roles)

Fixed in 42c06cce78294401eef3e803a4074717335006ea

**Comment by EventConsulting** [comment]
@christianwach Thx for the very quick response! :)
