### ISSUE TITLE
Preference for how to limit new users to individuals only

### ISSUE THREAD

**Issue by agh1** [christianwach/civicrm-wp-member-sync#26]
In your [support forum response about organizations getting assigned users](https://wordpress.org/support/topic/organizations-being-assigned/), it seemed that you view organizations having user accounts as a feature, not a bug.  While I disagree with doing it that way, I can imagine that some organizations have already committed to this.

I'm fairly confident that preferring that user accounts only correspond to individuals is more than just a niche preference ([it's how CiviCRM does the sync for existing users](https://github.com/civicrm/civicrm-core/blob/5.3.0/CRM/Utils/System/WordPress.php#L781)), and a client is having some serious problems stemming from users getting attached to organizations, so I'm planning on fixing it for them.

Would you be open to a pull request to this plugin that adds an option for whether to only create users for individuals, or would it be better to just write an extra plugin that uses the `civi_wp_member_sync_auto_create_wp_user` filter?

(An example of organization users being a problem: if you have an event with a profile with First Name and Last Name, and a logged-in user who is attached to an organization tries to register, they won't be able to do it since it's an Individual profile and won't show, but CiviEvent requires either your name or your email.)

**Comment by christianwach** [comment]
@agh1 I'm always open to PRs. What's the problem with using the filter?

**Comment by agh1** [comment]
@christianwach there's no problem with the filter.  I just figured this would be a super-common use case (and one we probably need to solve for a couple of additional clients besides the one who noticed problems) so the fix might as well be published for others.  I was just feeling out whether you felt that individuals-only was an edge case that should be solved with an extra plugin or a feature that would be welcome in your plugin.

**Comment by christianwach** [comment]
@agh1 Okay, I see what you mean. Yes, I can imagine an option on the Settings page would be welcome to many - as long as it defaults to the current state so it doesn't give existing users an unexpected surprise when they update!

**Comment by kcristiano** [comment]
@christianwach I agree a setting would be welcome.  I've had unexpected surprises with the new feature myself. :)  I prefer individuals only, but a choice would let us easily set this by client use case.

**Comment by christianwach** [comment]
Oops, that commit had a logic error - fixed in 6f9ae254cb0e6a5a2cef5768e190fd0308a6c753

**Comment by kcristiano** [comment]
Thanks @christianwach I have pushed this out to active staging sites that I had noticed Orgs syncing to WP users.   I'll update once I see results.

**Comment by kcristiano** [comment]
@christianwach I've tested on a couple of our staging sites and it looks good.   

Let me know when you push it up to the plugin repo as I need to reset the default option on most sites.

**Comment by christianwach** [comment]
@kcristiano Thanks for testing!

To automate the setting, you can make use of the code below:

For new installs, you can make use of the `civi_wp_member_sync_default_settings` filter to ensure that the option is enabled by default when the plugin is activated:

```php
add_filter( 'civi_wp_member_sync_default_settings', 'my_cwms_defaults' );

/**
 * Override default "types" setting.
 *
 * @param array $settings The default settings array.
 * @return array $settings The modified settings array.
 */
function my_cwms_defaults( $settings ) {
	$settings['types'] = 1;
	return $settings;
}
```

For existing installs, the code below ensures Contacts not of type "Individual" are not synced (code is copied and fixed from [the thread on wordpress.org](https://wordpress.org/support/topic/organizations-being-assigned/)):

```php
add_filter( 'civi_wp_member_sync_auto_create_wp_user', 'my_check_civicrm_contact_type', 10, 2 );

/**
 * Check what kind of Contact is being synced before creating WordPress user.
 *
 * @param bool $create_user True if user should be created by default.
 * @param int $contact_id The numeric ID of the CiviCRM Contact.
 * @return bool True if user should be created, false otherwise.
 */
function my_check_civicrm_contact_type( $create_user, $contact_id ) {
	
	// do not create user if no CiviCRM
	if ( ! civi_wp()->initialize() ) return false;

	// get contact data
	$contact = civicrm_api( 'contact', 'getsingle', array(
		'version' => 3,
		'contact_id' => $contact_id,
	) );
	
	// do not create user if we get an error
	if ( $contact['is_error'] == 1 ) return false;

	// allow only Individuals to be synced
	if ( $contact['contact_type'] != 'Individual' ) {
		$create_user = false;
	}

	return $create_user;
	
}
```

**Comment by christianwach** [comment]
@kcristiano On reflection, I'm leaning towards switching the default to "Individuals Only". Seems like both you and @agh1 are convinced that having Organisation users is actually the edge case. I will add an `admin_notice` to the next upgrade either way, since this is a critical setting for the correct functioning of this plugin.

**Comment by kcristiano** [comment]
>  On reflection, I'm leaning towards switching the default to "Individuals Only". 

This would work for all our current use cases, but consider others may already have started using Organizational logins, I don't think we should have this as the default.

**Comment by christianwach** [comment]
Version 0.3.6 defaults to "Individuals Only". I've added an Upgrade Notice to the plugin readme - hopefully people will pay attention to it!
