### ISSUE TITLE
class 'CiviCRM_WP_Profile_Sync' does not have a method 'wordpress_contact_updated'

### ISSUE THREAD

**Issue by mattwire** [christianwach/civicrm-wp-member-sync#32]
@christianwach This is throwing PHP warnings following this commit: https://github.com/christianwach/civicrm-wp-profile-sync/commit/6df5b5aeacf27766b8f465a206b30a36e52ad541

And indeed the method no longer exists because it has been renamed.

**Comment by christianwach** [comment]
@mattwire Thanks for the report. Should be fixed in 2e6fdf22c104d9a9af86932e9b658bb90d56da83 - can you check that it works for you?

**Comment by christianwach** [comment]
Closing as I assume this is fixed. @mattwire please reopen if I'm mistaken.
