### ISSUE TITLE
Users are not assigned specific role

### ISSUE THREAD

**Issue by shaneonabike** [christianwach/civicrm-wp-member-sync#34]
Hey there! Thanks so much for building an amazing plugin.

I seem to be running into a strange issue. I had imported members into the users table, as well as CiviCRM so I have identical records.

So we have member@example.com in CiviCRM as Home (Primary), and in Wordpress there is a corresponding user.

After that I manually added the membership record for each member since we are transition from an old system. When I ran the manual synchronization none of the users roles are changed. Does it make a difference that I am using custom roles using the Members plugin. I don't think it should b/c I haven't had any hiccups like this before. My config is:
+ Method: Roles
+ Synced Contact types: unchecked
+ Means of sync all checked and cron run per hour (although I manually ran it so it should just sync)

Example Association:
+ Membership Type: Member Level 1
+ Current status: New, Current, Grace checked
+ Wordpress Role: Paid Membership
+ Expire Status: all other checkboxes (except above) checked
+ Expiry Role: Limited

What am I missing? Is this a bug potentially? What more debug info can I provide.

**Comment by christianwach** [comment]
@shaneonabike Did you also add the UFMatch entries? That's CiviCRM's (and this plugin's) way of knowing which Contact maps to which User.

**Comment by shaneonabike** [comment]
Actually, I think I have two problems... the first being I was attempting to have Organizations match to a user in the system, but I think in general this isn't allowed by CiviCRM. I dealt with that issue and can confirm there are individual records like the following:

* Individual record : Employee of AB Organization
* AB Organization : Membership Type / etc set
* Individual record : Linked properly to Wordpress User ID (UFMatch)

I also unchecked the synced contact types so that it would do the organizations properly. What am I missing here?

**Comment by shaneonabike** [comment]
... And further testing shows me that if the Individual has a Membership then it works just fine so I think this has to do with the fact that it is the Organization who has the membership... Is there a way to provide further options so that we can test again the Employer having a membership and then giving the same access? I thought that was the nature of the "Synced Contact Types" checkbox.

**Comment by christianwach** [comment]
> I was attempting to have Organizations match to a user in the system, but I think in general this isn't allowed by CiviCRM.

@shaneonabike CiviCRM certainly assumes that WordPress Users are Individuals and treats them as such in its calls to `synchronizeUFMatch`. My advice would be that it's be better not to sync Orgs to WordPress.

> this has to do with the fact that it is the Organization who has the membership

Org Memberships should be inherited by Individuals. Are you finding that's not the case? You can replicate the "grouping" that is an Org in WordPress in other ways.

**Comment by shaneonabike** [comment]
Yeah I finally realized that this would not be possible without hacking things together. So I modified the process a bit and will record it here for others to see

+ Organization receives the membership
+ Membership Types are setup to give the membership (through the relationship) of Employee of
+ Then assign individual contacts to the organization
+ Rerunning the synchronization it now grants the proper membership role based on the membership type

Thanks so much for all the time that you have provided to give me solid answers I appreciate that!

**Comment by christianwach** [comment]
@shaneonabike Glad you're sorted and thanks for leaving a cookie trail for others.
