### ISSUE TITLE
Grant capability to WpUser it's synced if CiviContact has registered as an event participant (of certain role/statute)

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/civicrm-wp-member-sync#37]
Hi 

This may be slightly out of this specific module scop, and could also find it's place in civi-event-organiser plug-in, but either way the "need" is the same.
This module is a awesome way to restrict access to content based on Civi membership statut.

In the same vein, one may organize an event and restric access to some of it's site content to the ones that have registered.
At the moment, i don't think we can add a capability to a wp user based on his event registration role or statute.
Thus I can only think of creating a new membership type in Civi that you grant when one register to an event, it could work, but
- using membership type for this seems inappropriate/overkill
- if one cancel his event registration, it won't cancel it's membership at the same time, so it's a lot of extra "follow up" for the organizer of the event (or creating civi rules but that's not optimal anyhow)

So here we are, I wonder if you ever have thought of that, fell that need or a similar one, if/how you address it, or if it actually is a missing feature of Civi/WP integration that could be (must be ?) addresse throught this or civi-event-organiser plug-in ? 

Cheers

**Comment by christianwach** [comment]
> At the moment, i don't think we can add a capability to a wp user based on his event registration role or status.

@jbonlinea I think you're right that this functionality isn't available "out of the box". I'm sure it can be done using the hooks in CEO and/or CiviCRM, but haven't had the need for it so haven't looked closely at this issue. You might be able to do something with CiviRules in the meantime.

**Comment by jbonlinea** [comment]
Hi 
thank's for your reply

actually I've wonder fe times if/where I could find the list of available filters and hook for this plug-in (and all your civi related ones) ;

yes CiviRule could work, but I just bumped into a use case where event registration is suppose to giver user access to some part of the site content, and I think this might not be isolated due to the covid and off-site participation growth ;)

Cheers

**Comment by christianwach** [comment]
> the list of available filters and hook for this plug-in

@jbonlinea Just search the code for "apply_filters" and "do_action" :-)

**Comment by christianwach** [comment]
> event registration is suppose to giver user access to some part of the site content

How about this:

* _CiviRules_ adds Participant's Contact to a CiviCRM Group on registration
* _CiviCRM Groups Sync_ syncs the Contact to a _Groups_ Group
* The _Groups_ Group grants access to the hidden content

Seems like it should work.

**Comment by jbonlinea** [comment]
Hi there :)

This is about what I have done the first time I needed this feature but there were few limitations I can't remember at the moment, and civirules (still) do not play well with civicrm-wp-profile sync, I had open an issue [on your plug-in repo](https://github.com/christianwach/civicrm-wp-profile-sync/issues/33), as well as on the [CiviRules repo](https://lab.civicrm.org/extensions/civirules/-/issues/172) 

Thank's for the suggestion

Cheers

**Comment by christianwach** [comment]
@jbonlinea I left a bug report on the CiviRules issue.
