### ISSUE TITLE
two way sync with roles

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/civicrm-wp-member-sync#40]
Hi,

Lately I've wondered if the plug-in worked two way when using roles ? 
I mean when a the contact membership change, the role change, but also if a wp-user gets/loose a role its CiviConctact-membership changes to.

After testing I can say it is only Civi to Wp way, and I understand that to some extent.

Neverthless it has come to my mind to think that it would be awesome if it was two way ! it might seems a bit "brutal" as there is no consideration of duration and such, but most certainly ussefull in some case. I can develop, but I'm throwing this like this for the time being.

Cheers

**Comment by christianwach** [comment]
@jbonlinea Since most Memberships in CiviCRM involve Contributions, I think it's unlikely that this would be a useful feature for this plugin to implement. Building a separate (or slipstream) plugin that used the code in this plugin to achieve what you suggest is, of course, possible to do.

**Comment by jbonlinea** [comment]
Yes I do agree, this is a quite poor type of syncing, 

To it's defense it may be thought as the "force statute" option in civimembership, but well that poor and brutal.

Actually I thought of that because it could be a very simple way to sync civimerbeship to Paid Membership Pro, or maybe an other membership wp plugin.

The truth is that I have tested Paid Membership Pro which is feature rich and has an astonishing UX. And I really said to myself, damn with Civi we are miles away to e able to offer this UX, and this is one of the biggest downside of Civi for me.

If you ask me why would I evet want to sync and external plug-in and not simply forget about mebership in civi if PMP fit the bill, I'll reply you that Civi has a lot to offer for event management (with pricing, mailing, groups, etc) that I couldn't find anywhere else, and I need to know the membership statute in my event management workflow...

Ok this was simple a bottle to the see, sharing some stuff passing by my minds :)

**Comment by christianwach** [comment]
Closing since I don't envisage this happening, but thanks for the suggestion.
