### ISSUE TITLE
Member sync between separate Wordpress installations

### ISSUE THREAD

**Issue by jessefrissekom** [christianwach/civicrm-wp-member-sync#42]
We are currently working on a site new site for a client that uses CiviCRM data. The CiviCRM installation they currently have is rather large and we would like to keep it in a separate Wordpress installation so it does not impact the speed and stability of the site we are building. For this particular site CiviCRM contacts need to be able to sign in to Wordpress user accounts, thus we came across your plugin. Could you help us establish synchronisation between the CiviCRM contacts in one Wordpress installation and the Wordpress users on a Wordpress website?

**Comment by jessefrissekom** [comment]
@christianwach Thank you for responding so quickly. The setup is exactly as you described it. Yes, we would very much like to have all the CiviCRM contacts from the member site synced as users on the main site.

Main site -> Used as front-end for visitors and used by members to sign up for events etc. 
Membership site -> Used as CRM to manage members of an organisation 

Ideally an admin would add a new contact in CiviCRM and overnight the contact gets synced with the main site so the contact can login to Wordpress and sign up for events.

**Comment by christianwach** [comment]
@jessefrissekom Okay, I see. Personally, I'd advise against this sort of architecture. I see little benefit in it and many problems. Why not simply host the events on the members site if that's where sign-ups occur? And if they need to be on the main public site, why not hang CiviCRM off that? What speed and stability issues have you encountered?
