### ISSUE TITLE
Add Association Rule page not loading

### ISSUE THREAD

**Issue by dmpinder** [christianwach/civicrm-wp-member-sync#43]
When trying to load the "Add Association Rule" page (`page=civi_wp_member_sync_rules`), the page is coming up blank with no content. 

I'm not sure if I've missed a configuration somewhere, but I noticed that if I change `$mode` to have a default value of `add` on this line (https://github.com/christianwach/civicrm-wp-member-sync/blob/master/includes/civi-wp-ms-admin.php#L1115) then the page loads just fine. 

Can you let me know if I'm doing something wrong?

Thanks!

**Comment by dmpinder** [comment]
Update: rolling back to version 0.5.2 of the plugin works, so I suspect the issue is somewhere within the commit https://github.com/christianwach/civicrm-wp-member-sync/commit/305b9940b6c3c73b5afc6eb5e27240df3a209795

**Comment by christianwach** [comment]
@dmpinder Ouch! Thanks for the report - I'll have a look at this today... and yes, I suspect you're right about the commit that introduce the problem.

**Comment by christianwach** [comment]
@dmpinder I think a3d6a418acbacb2f58845a4cb32203fa27458b73 should fix things. I'll push to the WordPress Plugin Directory shortly.

**Comment by dmpinder** [comment]
@christianwach I can verify the fix, thanks for patching so promptly! 🙌

**Comment by christianwach** [comment]
Thanks for alerting me to this and for testing @dmpinder - new version is now on WordPress Plugin Directory.
