### ISSUE TITLE
Member sync not detecting roles correctly when using bbPress

### ISSUE THREAD

**Issue by wcha-peter** [christianwach/civicrm-wp-member-sync#46]
Hi,

Not sure if this one is a bbPress or member sync issue, but after activating bbPress, Member Sync seems to stop detecting wordpress roles correctly.

When attempting to set up a Role Association Rule with bbPress inactive, all the roles are showing up correctly:
![image](https://user-images.githubusercontent.com/95265029/213079065-cfb4df91-b4d9-4f4f-96a1-f58b58c97080.png)

However, after activating bbPress, only the bbPress forum roles are visible.
![image](https://user-images.githubusercontent.com/95265029/213079145-3127d9ee-5130-4809-8cc1-7ece325ed105.png)

This seems to happen both in the relativity complex multisite setup I initially tried it in, as well as a simple test site I set up. The info on the simple test site was:
- Wordpress v6.1.1
- CiviCRM v5.52.2
- CiviCRM Admin Utils v0.9.3
- CiviCRM WordPress Member Sync v0.5.4
- bbPress v2.6.9

Thanks for all the work on these plugins & civi integrations

**Comment by christianwach** [comment]
@wcha-peter Thanks for the report. I haven't tested this plugin with bbPress for some years now, but it does [try to exclude bbPress roles from the list](https://github.com/christianwach/civicrm-wp-member-sync/blob/2d519b0351b3686bf77f7b2906b8be07459944e3/includes/civi-wp-ms-users.php#L326-L341) in the select elements. Perhaps you could look at what's being returned by that method to see what's going on?

**Comment by christianwach** [comment]
Hmm, so it seems that `bbp_get_blog_roles()` [does the opposite](https://github.com/bbpress/bbPress/blob/394ae31c059228e866240076db2dc2ca2ddc8a7c/src/includes/core/capabilities.php#L254-L268) of what I must have imagined it did, and I mistakenly reversed the logic [in a recent code clean up](https://github.com/christianwach/civicrm-wp-member-sync/commit/45d3fcd95aebe83034790a8127f249072e6035a9#diff-96969b73846be59e6e691382f9c907fbb2905b8653d6e352238a84f5be9f43c6L366-L373). I'll push a fix today when I get a moment.

**Comment by christianwach** [comment]
@wcha-peter This should be fixed in 457b42d.

**Comment by wcha-peter** [comment]
Just tested it an looks like its working correctly. Thanks for your help.
