### ISSUE TITLE
no new user account email notification

### ISSUE THREAD

**Issue by lcdservices** [christianwach/civicrm-wp-member-sync#47]
I've discovered a few things in implementing this plugin recently that is not well documented, and I'm trying to understand the intention.

First, we found that new memberships will trigger the creation of a new user account if one does not exist. The manual synchronize settings page provides an option to create new user accounts. What's not clear is that the normal course of synchronization will always create a new user account (if one does not exist) -- there is no config option to control that.

Secondly, it appears that although a new user account is created, the user is not notified via the standard WP email. The wp_create_user() function references a hook that can be used to trigger wp_new_user_notification(), but it seems odd that it's not simply done automatically as is the case with most other new user creation tasks.

Anyway, before I work on modifications for this client, I wanted to see if I'm missing anything, and what the rationale was for these decisions.

**Comment by christianwach** [comment]
> First, we found that new memberships will trigger the creation of a new user account if one does not exist. The manual synchronize settings page provides an option to create new user accounts. What's not clear is that the normal course of synchronization will always create a new user account (if one does not exist) -- there is no config option to control that.

Config is via [this filter](https://github.com/christianwach/civicrm-wp-member-sync/blob/10747b2ce7de393ea433a07f12a29fc3faaefd39/includes/civi-wp-ms-users.php#L666).

> Secondly, it appears that although a new user account is created, the user is not notified via the standard WP email. The wp_create_user() function references a hook that can be used to trigger wp_new_user_notification(), but it seems odd that it's not simply done automatically as is the case with most other new user creation tasks.

There are many ways to do this (via CiviCRM or WordPress) so it is left to others to implement in their chosen manner.
