### ISSUE TITLE
Ability to add additional Membership Type transitions after intial setup

### ISSUE THREAD

**Issue by shaneonabike** [christianwach/civicrm-wp-member-sync#53]
Thanks for this great extension it really helps in settings roles in Wordpress.

So I have a client who has the following

+ Membership A
+ Membership B

## Present system

Using a ```role``` based integration you can choose the transition of Membership(s) for Current and Expired.

We have :

+ Membership A & B (New & Current) -> Member (Active)
+ Membership A & B (Expired, Pending, Cancelled, Deceased) -> Member (Expired)

## What they want

Is the ability to add another set like the following:

+ Membership A & B (Grace) -> Member (Grace)
+ Membership A & B (Expired, ...) -> Member (Expired)

I'm thinking you didn't want to do that b/c it could create a bit of chaos in processing. I think the Drupal equivalent kinda lets you do that and it's based on the order of things.

In their case, they want to provide specific permissions and display/hide certain things if you are in Grace mode.

**Comment by kcristiano** [comment]
@shaneonabike I use https://develop.tadpole.cc/plugins/civicrm-member-sync-single-role   in the above use case.  IIRC if there is only one current membership it uses the current membership not the expired.   if there are multiple current memberships, the "winner' is the latest expiry date.

It's an add-on plugin as it does not fit all use cases.  this work was funded by a client that needed exactly this, but I've ended up making use of it on a decent number of sites.  

If this works, great, but we don't plan any changes or additions to this plugin right now.

**Comment by christianwach** [comment]
> I'm thinking you didn't want to do that

@shaneonabike No, I didn't do that because it didn't occur to me and I haven't had such a request in the 10 years that this plugin has been published! 

I hope your client's unusual needs are met by the plugin that @kcristiano commissioned me to write.

**Comment by shaneonabike** [comment]
@christianwach You took my sentence a bit out of context without the entire sentence ;). I was just trying to determine if it would be problematic to set it up that way -- we had issues before with Drupal. 

I'll give @kcristiano's suggestion a spin and see if that does the job, which I think it probably will. Thanks so much for your fast responses it's greatly appreciated.

**Comment by shaneonabike** [comment]
Hi there,

So I tried this extension and it works great, but actually my scenario is a bit different. Essentially, I want to be able to assign a different role based on the actual status of the member.

+ Membership Grace => Grace role (WP)
+ Membership New/Active => Active role (WP)
+ Membership Expired/Deceased/... => Expired role (WP)

Is that possible via a hook or some other method?

**Comment by kcristiano** [comment]
@shaneonabike I'd think the best way would be to create your own plugin that is modeled after the one I referenced, but set the criteria to what you need.

**Comment by christianwach** [comment]
@shaneonabike I second Kevin's assessment.

**Comment by shaneonabike** [comment]
Great thanks so much for your suggestions have a great weekend. I'll close this now.
